name: Build statically-linked mosh binaries
on:
  [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: buildjet-2vcpu-ubuntu-2204
          - arch: aarch64
            runs-on: buildjet-2vcpu-ubuntu-2204-arm

    name: Build on ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/eggbean/mosh/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t builder .
          git clone --depth=1 https://github.com/eggbean/mosh.git
          docker run -v $PWD/mosh:/mosh -w /mosh --name=builder builder sh -c './autogen.sh && LDFLAGS=-static ./configure && make'
      - run: |
          (
            echo '- [${{ env.version }} build](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            echo '- [Workflow file](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/.github/workflows/autobuild.yml)'
            echo
            echo '## ${{ matrix.arch }} files'
            echo '```'
            (cd mosh/src/frontend && file mosh-server mosh-client)
            echo '```'
            echo
            echo '## ${{ matrix.arch }} SHA256 checksums'
            echo '```'
            (cd mosh/src/frontend && sha256sum mosh-server mosh-client)
            echo '```'
          ) | tee details-${{ matrix.arch }}.txt

      - name: Gather files
        run: |
          mkdir -p files/{man,bash-completion}
          mv mosh/conf/bash-completion/completions/mosh files/bash-completion
          mv mosh/scripts/mosh files
          mv mosh/src/frontend/mosh-client files
          mv mosh/src/frontend/mosh-server files
          mv mosh/man/mosh.1 files/man
          mv mosh/man/mosh-client.1 files/man
          mv mosh/man/mosh-server.1 files/man
          gzip files/man/mosh*.1

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: mosh-static-${{ matrix.arch }}
          path: ./files
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/eggbean/mosh/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Download packages
        uses: actions/download-artifact@v3

      - name: Create tarballs
        run: |
          cd ./mosh-static-x86_64
          chmod +x mosh{,-server,-client}
          tar -cvzf ../mosh-static-x86_64.tar.gz .
          cd ../mosh-static-aarch64
          chmod +x mosh{,-server,-client}
          tar -cvzf ../mosh-static-aarch64.tar.gz .

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          files: |
            mosh-static-x86_64.tar.gz
            mosh-static-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
